Update terraform-pre-plan
added the verifivation of using external provider

diff --git a/hooks/terraform-pre-plan b/hooks/terraform-pre-plan
--- a/hooks/terraform-pre-plan
+++ b/hooks/terraform-pre-plan
@@ -12,7 +12,18 @@ if [ ! -z "$FILES" ]; then
         echo -e "\e[0;35m ---------Pre-Plan End ----------\033[0m"
         exit 1
 fi
+FILES=`find . -type f -exec grep -l "external" {} \;`
+if [ ! -z "$FILES" ]; then
+        echo -e "\e[0;31mFAILED due to usage of forbidden provider \"external\" \033[0m"
+        echo
+        echo "List of Invalid File(s):"
+        echo $FILES
+        echo
+        echo -e "\e[0;35m ---------Pre-Plan End ----------\033[0m"
+        exit 1
+fi
 echo
 echo " Pre plan success !"
 echo
 echo -e "\e[0;35m ---------Pre-Plan End ----------\033[0m"
+exit 0
